accounts/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from . import views
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.homeView, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('deleteaccount/', views.delete_user, name='deleteaccount'),
    path('dashboard/<str:username>', views.dashboard, name='dashboard'),
    path('profileAction/follow/<str:username>', views.followRequest, name='followUser')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bits/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from . import views
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
app_name = 'bits'
urlpatterns = [
    path('timeline', views.getTheLatestTweetsFromFollowing, name='timeline'),
    path('<str:username>', views.publicProfileView, name='publicProfileView'),
    path('bitActionLike/<int:bitPk>', views.likeBit, name='likeBit'),
    path('bitActionReBit/<int:bitPk>', views.reBit, name='reBit'),
    path('profile/<str:username>/new', views.newBit, name='newBit'),
    path('profile/<str:username>', views.publicProfileViewLoggedIn, name='internalProfileView'),
    # 127.0.0.1:8000/api/user/lol21/following
    path('api/user/<str:apiKey>/following/', views.getApiBits, name='getApiBits'),
    # 127.0.0.1:8000/api/user/lol21
    path('api/user/<str:apiKey>', views.apiUserProfile, name='apiUserProfile'),
    # 127.0.0.1:8000/api/user/lol21/new/I_sent_this_via_the_API_!
    path('api/user/<str:apiKey>/new/<str:message>', views.apiNewBit, name='apiNewBit')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libertas/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django.urls import path
from django.urls import include
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('bits.urls'))
]

accounts/models.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django.db import models
from django.utils import timezone
from .managers import CustomUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
class LibertasUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=300,unique=True)
    bio = models.CharField(max_length=300,unique=True)
    apiAuth = models.CharField(max_length=16,unique=True)
    follower = models.ForeignKey(to='LibertasUser',on_delete=models.CASCADE,related_name='followerNew', null=True, blank=True)
    following = models.ForeignKey(to='LibertasUser',on_delete=models.CASCADE,related_name='followingNew', null=True, blank=True)
    profile_pic = models.ImageField(upload_to='images/profile_pictures')
    banner_pic = models.ImageField(upload_to='images/banner_pictures')
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()
    def __str__(self):
        return self.username

accounts/forms.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django import forms
from .models import LibertasUser
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
class NewUserForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = LibertasUser
        labels = {
          'username':'Username',
          'bio':'About',
          'apiAuth':'Auth',
          'profile_pic':'Profile Picture',
          'banner_pic':'Banner Picture'
        }
        fields = (
        'username',
        'bio',
        'apiAuth',
        'profile_pic',
        'banner_pic',
        )
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None
class OldUserChangeForm(UserChangeForm):
    class Meta:
        model = LibertasUser
        fields = ('username',)

accounts/views.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from .forms import *
from django import forms
from bits.models import Bit
from django.utils.http import *
from django.utils.encoding import *
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth import logout
from accounts.models import LibertasUser
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site

def homeView(request):
    return render(request, 'accounts/home.html')
def register_user(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            return redirect('accounts:dashboard', username=username)
        else:
            print(form.errors)
            pwd_one = form.cleaned_data.get('password1')
            pwd_two = form.cleaned_data.get('password2')
    form = NewUserForm
    return render(request, 'accounts/register.html', context={'form':form})
def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username =form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return redirect('accounts:dashboard', username=username)
            else:
                pass
        else:
            pass
    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})
@login_required
def logout_user(request):
    logout(request)
    return redirect('accounts:home')
@login_required
def delete_user(request):
    username = request.user.username
    u = LibertasUser.objects.get(username=username)
    u.delete()
    return redirect('accounts:home')
@login_required
def followRequest(request, username):
    you = LibertasUser.objects.get(username=request.user.username)
    alienUser = LibertasUser.objects.get(username=username)
    try:
        you.following = alienUser
        you.save()
        alienUser.follower = you
        alienUser.save()
        return redirect('bits:internalProfileView', username=username)
    except Exception as error:
        return redirect('accounts:dashboard', username=you.username)
@login_required
def dashboard(request, username):
    username = request.user.username
    apiAuth = request.user.apiAuth
    profile_pic = request.user.profile_pic.url
    banner_pic = request.user.banner_pic.url
    bio = request.user.bio
    bits = Bit.objects.all().filter(sender=request.user.pk)
    return render(request, 'accounts/dashboard.html', {'username':username, 'bio':bio, 'apiAuth':apiAuth, 'profile_pic':profile_pic, 'bits':bits, 'banner_pic':banner_pic})

templates/accounts/dashboard.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>

    <div class="menuRibbon">
     <h1 class="general">YOUR DASHBOARD</h1>
    </div>

    <div class="profileBanner">
     <img class="profileBanner" src="{{ banner_pic }}"/>
    </div>

    <div class="userInfo">
     <img class="profilePicture" src="{{ profile_pic }}"/>
     <p class="username">{{ username }}</p>
     <p class="bio">{{ bio }}</p>
     <p class="followInfo">API Key: {{ apiAuth }}</p>
    </div>

    <div class="accountActions">
     <button class="accountAction" onclick="window.location.href='{% url 'bits:timeline' %}'">Timeline</button>
     <button class="accountAction" onclick="window.location.href='{% url 'bits:internalProfileView' username=request.user.username %}'">Profile</button>
     <button class="accountAction" onclick="window.location.href='{% url 'accounts:logout' %}'">Logout</button>
     <button class="accountAction" onclick="window.location.href='{% url 'accounts:deleteaccount' %}'">Delete Account</button>
     <button class="accountAction" onclick="window.location.href='{% url 'bits:newBit' username=request.user.username %}'">New Bit</button>
     </body>
    </div>

    {% if bits.all %}
     {% for bit in bits.all %}
      <div class="bit">
       <img class="bitProfilePicture" src="{{ profile_pic }}"/>
       <p class="bitUserName">@{{ username }}</p>
       <p class="bit">{{ bit.bitBody }}</p>
       <hr/>
      </div>
     {% endfor %}
    {% else %}
     <div class="bit">
      <img class="bitProfilePicture" src="{{ profile_pic }}"/>
      <p class="bitUserName">@{{ username }}</p>
      <p class="bit">No bits yet. :(</p>
      <hr/>
    </div>
   {% endif %}

   </body>
  </html>
{% endblock %}

templates/accounts/home.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>
     <div class="banner">
      <img class="landingBanner" src="https://blckunicorn.art/assets/libertas/images/banner/kitsune.svg"/>
     </div>
     <div class="loginActionDiv">
      <div class="content">
       <h1>LIBERTAS</h1>
        <p>Libertas, a social network about freedom of expression.</p>
        <button class="actionNew" onclick="window.location.href='{% url 'accounts:login' %}'">LOGIN</button>
        <button class="actionNew" onclick="window.location.href='{% url 'accounts:register' %}'">REGISTER</button>
      </div>
     </div>
   </body>
  </html>
{% endblock %}

templates/accounts/login.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>

    <div class="banner">
     <img class="landingBanner" src="https://blckunicorn.art/assets/libertas/images/banner/kitsune.svg"/>
    </div>

    <div class="loginActionDiv">

     <div class="content">
      <h1>LOGIN</h1>
      <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}
      <button class="action" type="submit">Login</button>
     </form>
    </div>

   </div>

  </body>
 </html>
{% endblock %}

templates/accounts/register.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>

    <div class="banner">
     <img class="landingBanner" src="https://blckunicorn.art/assets/libertas/images/banner/kitsune.svg"/>
    </div>

    <div class="loginActionDiv">

     <div class="content">
      <h1>REGISTER</h1>
      <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
      <button class="action" type="submit">Register</button>
     </form>
    </div>

   </div>

  </body>
 </html>
{% endblock %}