accounts/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from . import views
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.homeView, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('deleteaccount/', views.delete_user, name='deleteaccount'),
    path('dashboard/<str:username>', views.dashboard, name='dashboard'),
    path('profileAction/follow/<str:username>', views.followRequest, name='followUser')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bits/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from . import views
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
app_name = 'bits'
urlpatterns = [
    path('timeline', views.getTheLatestTweetsFromFollowing, name='timeline'),
    path('<str:username>', views.publicProfileView, name='publicProfileView'),
    path('bitActionLike/<int:bitPk>', views.likeBit, name='likeBit'),
    path('bitActionReBit/<int:bitPk>', views.reBit, name='reBit'),
    path('profile/<str:username>/new', views.newBit, name='newBit'),
    path('profile/<str:username>', views.publicProfileViewLoggedIn, name='internalProfileView'),
    # 127.0.0.1:8000/api/user/lol21/following
    path('api/user/<str:apiKey>/following/', views.getApiBits, name='getApiBits'),
    # 127.0.0.1:8000/api/user/lol21
    path('api/user/<str:apiKey>', views.apiUserProfile, name='apiUserProfile'),
    # 127.0.0.1:8000/api/user/lol21/new/I_sent_this_via_the_API_!
    path('api/user/<str:apiKey>/new/<str:message>', views.apiNewBit, name='apiNewBit')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libertas/urls.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django.urls import path
from django.urls import include
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('bits.urls'))
]

bits/models.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django.db import models
from accounts.models import LibertasUser
class Bit(models.Model):
    bitBody = models.CharField(max_length=200000)
    bitPic = models.ImageField(verbose_name='bitPic', upload_to='images/bit_pictures', null=True, blank=True)
    sender = models.ForeignKey(LibertasUser,on_delete=models.CASCADE,related_name='sender')
    date = models.DateTimeField(verbose_name='date',auto_now=True)
    def __str__(self):
        return bitBody

class BitLike(models.Model):
    bitData = models.ForeignKey(Bit,on_delete=models.CASCADE,related_name='likedBit', null=True, blank=True)
    userWhoLiked = models.ForeignKey(LibertasUser,on_delete=models.CASCADE,related_name='liker', null=True, blank=True)

bits/forms.py
# Libertas by Alexander Abraham, "The Black Unicorn".
# Licensed under the MIT license.
from django import forms
from .models import Bit
class BitForm(forms.ModelForm):
    #subject = forms.CharField(label='New Bit', max_length=2000 , widget=forms.TextInput(attrs={'class':'newBit'}))
    class Meta:
        model = Bit
        labels = {
            'bitBody':'Your Bit',
            'bitPic':'Add an image'
        }
        fields = ('bitBody','bitPic')
    def __init__(self, *args, **kwargs):
        super(BitForm, self).__init__(*args, **kwargs)
        self.fields['bitPic'].required = False
        #self.fields['bitBody'].attrs['class'] = 'newBit'

bits/views.py
from .forms import *
from django.db import models
from .models import Bit
from .models import BitLike
from django.utils.http import *
from django.utils.encoding import *
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import redirect
from accounts.models import LibertasUser
from django.contrib.auth.decorators import login_required

def newBit(request, username):
    if request.method == "POST":
        form = BitForm(request.POST)
        if form.is_valid():
            bitBody = form.save(commit=False)
            bitBody.sender = request.user
            bitBody.save()
            return redirect('bits:internalProfileView', username=username)
    else:
        form = BitForm()
    return render(request, 'bits/new.html', {'form': form})
@login_required
def publicProfileViewLoggedIn(request, username):
    loggedInUser = request.user.username
    alien = LibertasUser.objects.get(username=username)
    bits = Bit.objects.all().filter(sender=alien.pk)
    profile_pic = alien.profile_pic.url
    banner_pic = alien.banner_pic.url
    bio = LibertasUser.objects.get(username=username).bio
    followerCount = 0
    followingCount = 0
    bitLikeDict = []
    for i in bits:
        bitPk = i.pk
        bitText = i.bitBody
        bitSender = i.sender.username
        likeCount = BitLike.objects.filter(bitData=Bit.objects.get(pk=bitPk)).all().count()
        if likeCount:
            bitLikeDict = bitLikeDict + [[bitText,likeCount,bitSender,bitPk]]
        else:
            bitLikeDict = bitLikeDict + [[bitText,likeCount,bitSender,bitPk]]
    followerCount = LibertasUser.objects.filter(following=alien.pk).all().count()
    followingCount = LibertasUser.objects.filter(follower=alien.pk).all().count()
    print(bitLikeDict)
    return render(request, 'bits/internalProfile.html', {'bits': bitLikeDict, 'bio':bio, 'username': username, 'profile_pic':profile_pic, 'banner_pic':banner_pic, 'followerCount':followerCount, 'followingCount':followingCount, 'loggedInUserName':loggedInUser})


@login_required
def likeBit(request, bitPk):
    liker = LibertasUser.objects.get(username=request.user.username)
    bitToLike = Bit.objects.get(pk=bitPk)
    bitOwner = Bit.objects.get(pk=bitPk).sender
    try:
        newLike = BitLike(bitData=bitToLike, userWhoLiked=liker)
        newLike.save()
        print('Success!')
        return redirect('bits:internalProfileView', username=bitOwner)
    except Exception as error:
        print(str(error))
        return redirect('accounts:dashboard', username=liker.username)
@login_required
def reBit(request, bitPk):
    currentUser = request.user
    originalUser = Bit.objects.get(pk=bitPk).sender
    newBit = Bit(
        bitBody=Bit.objects.get(pk=bitPk).bitBody,
        bitPic=Bit.objects.get(pk=bitPk).bitPic,
        sender=currentUser,
        date=models.DateTimeField(verbose_name='date',auto_now=True)
    )
    try:
        newBit.save()
        return redirect('bits:internalProfileView', username=originalUser)
    except Exception as error:
        print(str(error))
        return redirect('accounts:dashboard', username=currentUser.username)
@login_required
def getTheLatestTweetsFromFollowing(request):
    username = request.user.username
    profile_pic = request.user.profile_pic.url
    bitList = []
    you = LibertasUser.objects.get(username=username)
    allUsersFollowed = LibertasUser.objects.all().filter(follower=you.pk)
    for i in allUsersFollowed:
        userObject = i
        bitterProfilePic = userObject.profile_pic.url
        bit = Bit.objects.filter(sender=userObject.pk).order_by('date').first()
        likeCount = BitLike.objects.filter(bitData=bit).all().count()
        bitList = bitList + [[bit.bitBody, bit.sender, bit.pk, likeCount, bitterProfilePic]]
    print(bitList)
    return render(request, 'bits/timeline.html', {'bits':bitList, 'username':username, 'profile_pic':profile_pic})
@login_required
def publicProfileView(request, username):
    alien = LibertasUser.objects.get(username=username)
    bio = LibertasUser.objects.get(username=username).bio
    bits = Bit.objects.all().filter(sender=alien.pk)
    profile_pic = alien.profile_pic.url
    banner_pic = alien.banner_pic.url
    followerCount = 0
    followingCount = 0
    bitLikeDict = []
    for i in bits:
        bitPk = i.pk
        bitText = i.bitBody
        bitSender = i.sender.username
        likeCount = BitLike.objects.filter(bitData=Bit.objects.get(pk=bitPk)).all().count()
        if likeCount:
            bitLikeDict = bitLikeDict + [[bitText,likeCount,bitSender,bitPk]]
        else:
            bitLikeDict = bitLikeDict + [[bitText,likeCount,bitSender,bitPk]]
    followerCount = LibertasUser.objects.filter(following=alien.pk).all().count()
    followingCount = LibertasUser.objects.filter(follower=alien.pk).all().count()
    return render(request, 'bits/publicProfile.html', {'bits': bitLikeDict, 'bio':bio, 'username': username, 'profile_pic':profile_pic, 'banner_pic':banner_pic, 'followerCount':followerCount, 'followingCount':followingCount})

def apiUserProfile(request,apiKey):
    try:
        origin = request.get_host()
        user = LibertasUser.objects.get(apiAuth=apiKey)
        username = user.username
        userProfilePic = origin + user.profile_pic.url
        userBannerPic = origin + user.banner_pic.url
        userBits = Bit.objects.all().filter(sender=user.pk)
        responseList = []
        for i in userBits:
            bitBody = i.bitBody
            bitDate = i.date
            responseList = responseList + [[bitBody, bitDate]]
        response = {
            apiKey:[username,userProfilePic, userBannerPic],
            'bits':responseList
        }
        return JsonResponse(response)
    except Exception as error:
        print(str(error))
        response = {'404':'Error'}
        return JsonResponse(response)

def getApiBits(request,apiKey):
    try:
        origin = request.get_host()
        you = LibertasUser.objects.get(apiAuth=apiKey)
        followingUsers = LibertasUser.objects.all().filter(following=you)
        response = {}
        for i in followingUsers:
            alienUserName = i.username
            alienProfilePicture = origin + i.profile_pic.url
            alienBitList = []
            alienBits = Bit.objects.all().filter(sender=i)
            for alienBit in alienBits:
                alienBitBody = alienBit.bitBody
                alienBitDate = alienBit.date
                alienBitList = alienBitList + [[alienBitBody, alienBitDate]]
            response[alienUserName] = [
                {'profile_pic':alienProfilePicture,'bits':alienBitList}
            ]
        return JsonResponse(response)
    except Exception as error:
        print(str(error))
        response = {'404':'Error'}
        return JsonResponse(response)

def apiNewBit(request,apiKey, message):
    try:
        body = ' '.join(message.split('_'))
        newBit = Bit(
            bitBody=body,
            sender=LibertasUser.objects.get(apiAuth=apiKey),
            date=models.DateTimeField(verbose_name='date',auto_now=True)
        )
        newBit.save()
        response = {'200':'OK'}
        return JsonResponse(response)
    except Exception as error:
        print(str(error))
        response = {'500':'Error'}
        return JsonResponse(response)

templates/bits/internalProfile.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>
     <div class="profileBanner">
      <img class="profileBanner" src="{{ banner_pic }}"/>
     </div>

     <div class="userInfo">
      <img class="profilePicture" src="{{ profile_pic }}"/>
      <p class="username">{{ username }}</p>
      <p class="bio">{{ bio }}</p>
      <p class="followInfo">Followers: {{ followerCount }} Following: {{ followingCount }}</p>
     </div>

     <div class="accountActions">
      <button class="accountAction" onclick="window.location.href='{% url 'accounts:dashboard' username=loggedInUserName %}'">Dashboard</button>
      <button class="accountAction" onclick="window.location.href='{% url 'accounts:followUser' username=username %}'">Follow</button>
     </div>

    {% if bits %}

     {% for item in bits %}

     <div class="bit">
      <img class="bitProfilePicture" src="{{ profile_pic }}"/>
      <p class="bitUserName">@{{ username  }}</p>
      <p class="bit">You haven't posted anything yet.</p>
      <hr/>
     </div>

     {% endfor %}

    {% else %}

     <div class="bit">
      <img class="bitProfilePicture" src="{{ profile_pic }}"/>
      <p class="bitUserName">@{{ username }}</p>
      <p class="bit"><p>No bits posted by this user yet!</p></p>
      <hr/>
     </div>

    {% endif %}

   </body>
  </html>
{% endblock %}

templates/bits/new.html
{% block content %}
 <!DOCTYPE html>
  <html>

   {% include "accounts/includes/header.html" %}

   <body>

    <div class="menuRibbon">
     <h1 class="general">WRITE A NEW BIT</h1>
    </div>

    <div class="newBit">
     <h1 class="newBit">NEW BIT</h1>
     <div class="newBitForm">
      <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       <button class="newBit" type="submit">Save</button>
      </form>
     </div>
    </div>

  </html>
{% endblock %}

templates/bits/profile.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>
     <h1>@{{ username }}</h1>
     {% for bit in bits.all %}
      <p>{{ bit.bitBody }}<a href="{% url 'bits:newBit' username=request.user.username %}">Answer</a></p>
     {% endfor %}
   </body>
  </html>
{% endblock %}

templates/bits/profileHome.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>
     <h1>@{{ username }}</h1>
     {% if content %}
      {% for object in content %}
      <p>{{ object.bitBody }} by {{ object.sender }}</p>
      {% endfor %}
     {% else %}
     {% endif %}
   </body>
  </html>
{% endblock %}

templates/bits/publicProfile.html
{% block content %}
 <!DOCTYPE html>
  <html>
   {% include "accounts/includes/header.html" %}
   <body>
     <div class="profileBanner">
      <img class="profileBanner" src="{{ banner_pic }}"/>
     </div>

     <div class="userInfo">
      <img class="profilePicture" src="{{ profile_pic }}"/>
      <p class="username">{{ username }}</p>
      <p class="bio">{{ bio }}</p>
      <p class="followInfo">Followers: {{ followerCount }} Following: {{ followingCount }}</p>
     </div>


    {% if bits.all %}

     {% for item in bits.all %}

      <div class="bit">
       <img class="bitProfilePicture" src="{{ profile_pic }}"/>
       <p class="bitUserName">@{{ item.2 }}</p>
       <p class="bit">{{ item.0 }}</p>
       <hr/>
       <button onclick="window.location.href='{% url 'bits:reBit' bitPk=item.3 %}'" class="bitAction">ReBit</button>
       <button onclick="window.location.href='{% url 'bits:likeBit' bitPk=item.3 %}'" class="bitAction">Like</button>
       <p class="bitAction">{{ item.1 }}</p>
      </div>

     {% endfor %}

    {% else %}

    <div class="bit">
     <img class="bitProfilePicture" src="{{ profile_pic }}"/>
     <p class="bitUserName">@{{ username  }}</p>
     <p class="bit">{{ username }} hasn't posted anything yet.</p>
     <hr/>
    </div>

    {% endif %}

   </body>
  </html>
{% endblock %}

templates/bits/timeline.html
{% block content %}
 <!DOCTYPE html>
  <html>

   {% include "accounts/includes/header.html" %}

   <body>

   {% if bits %}

   {% for bit in bits %}

   <div class="bit">
    <img class="bitProfilePicture" src="{{ bit.4 }}"/>
    <p class="bitUserName">{{ bit.1 }}</p>
    <p class="bit">{{ bit.0 }}</p>
    <hr/>
    <button onclick="window.location.href='{% url 'bits:reBit' bitPk=bit.2 %}'" class="bitAction">ReBit</button>
    <button onclick="window.location.href='{% url 'bits:reBit' bitPk=bit.2 %}'" class="bitAction">Like</button>
    <p class="bitAction">{{ bit.3 }}</p>
   </div>

   {% endfor %}

   {% else %}
   <div class="bit">
    <img class="bitProfilePicture" src="{{ request.user.profile_pic.url }}"/>
    <p class="bitUserName">@{{ request.user.username  }}</p>
    <p class="bit">You're not following anyone yet.</p>
    <hr/>
   </div>
   {% endif %}

   </body>
  </html>
{% endblock %}